### ISSUE TITLE
knock-knock paralle not working

### ISSUE THREAD

**Issue by hukai916** [jeffhussmann/knock-knock#10]
Hi Jeff,

I also tested the `parallel` commands, it pops the following error and failed to run:
```
knock-knock parallel test_ep300a 1 --group pacbio
Traceback (most recent call last):
  File "/opt/conda/bin/knock-knock", line 236, in <module>
    args.func(args)
  File "/opt/conda/bin/knock-knock", line 32, in parallel
    exps = knock_knock.experiment.get_all_experiments(args.project_directory, args.conditions)
  File "/opt/conda/lib/python3.10/site-packages/knock_knock/experiment.py", line 1650, in get_all_experiments
    exp = exp_class(base_dir, batch, name, description=description, progress=progress)
  File "/opt/conda/lib/python3.10/site-packages/knock_knock/experiment.py", line 139, in __init__
    features_to_show=self.target_info.features_to_show,
  File "/opt/conda/lib/python3.10/site-packages/hits/utilities.py", line 190, in memoized_f
    setattr(self, attr_name, f(self))
  File "/opt/conda/lib/python3.10/site-packages/knock_knock/experiment.py", line 206, in target_info
    supplemental_indices=self.supplemental_indices,
  File "/opt/conda/lib/python3.10/site-packages/hits/utilities.py", line 190, in memoized_f
    setattr(self, attr_name, f(self))
  File "/opt/conda/lib/python3.10/site-packages/knock_knock/experiment.py", line 194, in supplemental_indices
    return {name: locations[name] for name in self.supplemental_index_names}
TypeError: 'int' object is not iterable
```

Any input?

**Comment by jeffhussmann** [comment]
Consolidating discussion in https://github.com/jeffhussmann/knock-knock/issues/12.
