### ISSUE TITLE
Example files not up to date

### ISSUE THREAD

**Issue by hukai916** [jeffhussmann/knock-knock#11]
Hi Jeff,

Can you take some time to update the example files and documentation? The current version is barely working with v0.3.8. For example, when I tried to build target, I keep getting:
```
knock-knock build-targets test_dir
/opt/conda/lib/python3.10/site-packages/knock_knock/build_targets.py:1043: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  registry['sgRNA_sequence'] = pd.read_csv(sgRNA_fn, index_col='name', squeeze=True)
/opt/conda/lib/python3.10/site-packages/knock_knock/build_targets.py:1050: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  registry['amplicon_primers'] = pd.read_csv(amplicon_primers_fn, index_col='name', squeeze=True)
Traceback (most recent call last):
  File "/opt/conda/bin/knock-knock", line 236, in <module>
    args.func(args)
  File "/opt/conda/bin/knock-knock", line 122, in build_targets
    build_targets.build_target_infos_from_csv(args.project_directory,
  File "/opt/conda/lib/python3.10/site-packages/knock_knock/build_targets.py", line 1142, in build_target_infos_from_csv
    for pegRNA_name, pegRNA_components in info['pegRNAs']:
TypeError: 'NoneType' object is not iterable
```

Thank you!

**Comment by jeffhussmann** [comment]
Consolidating discussion in https://github.com/jeffhussmann/knock-knock/issues/12.
