### ISSUE TITLE
pegRNAs are not defined in example data

### ISSUE THREAD

**Issue by ShanSabri** [jeffhussmann/knock-knock#4]
```
$ knock-knock build-indices $PROJECT_DIR $ORGANISM --num-threads $NUM_THREADS
Downloading hg38...
Uncompressing...
Building indices for hg38
Indexing fastas...
Building STAR index...
Building minimap2 index...

$ knock-knock build-targets $PROJECT_DIR
Traceback (most recent call last):
  File "/home/ubuntu/.Anaconda3/bin/knock-knock", line 236, in <module>
    args.func(args)
  File "/home/ubuntu/.Anaconda3/bin/knock-knock", line 122, in build_targets
    build_targets.build_target_infos_from_csv(args.project_directory,
  File "/home/ubuntu/.Anaconda3/lib/python3.8/site-packages/knock_knock/build_targets.py", line 1142, in build_target_infos_from_csv
    for pegRNA_name, pegRNA_components in info['pegRNAs']:
TypeError: 'NoneType' object is not iterable
```

Any insight on how best to proceed?

**Comment by ShanSabri** [comment]
Ended up downgrading to `knock-knock==0.3.6`
